### ISSUE TITLE
CC1352P-2 Obsolete 

### ISSUE THREAD

**Issue by alemairebe** [Koenkk/Z-Stack-firmware#289]
Hello !

I was looking at improving my setup and switching from my CC2531 to a more powerful, stable, recent hardware.
I looked for CC1352P-2 as it is from my understanding supporting latest firmware and has powerful antenna.
On TI site, it is out of stock and on [Mouser](https://www.mouser.be/ProductDetail/Texas-Instruments/LAUNCHXL-CC1352P-2?qs=%2Fha2pyFaduiQ7Z42YDZKD4Eo7IvMXe9gZsQzNWwKV0QVOiPerDrdGqRCsGnjO5xy) it is even marked as obsolete.

Would LAUNCHXL-CC1352P1 or LAUNCHXL-CC1352P-4 support the same firmware as LAUNCHXL-CC1352P-2 ?

**Comment by Koenkk** [comment]
The P4 and P1 don't make sense for a Zigbee2MQTT use case since only the P2 has the full amplifier for 2.4 ghz. Note that this is the only difference between these versions.

![image](https://user-images.githubusercontent.com/2892853/118676480-ba960400-b7fb-11eb-96f4-4b4afd41a908.png) (https://www.ti.com/tool/LAUNCHXL-CC1352P)

If you really want the amplifier (which shouldn't be needed for most use cases), and you cannot get a CC1352P you can go for a CC2652P. See 3rd point of https://www.zigbee2mqtt.io/information/supported_adapters.html#notes
